# Generated by Django 2.2.14 on 2020-07-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='port',
            field=models.IntegerField(unique=True),
        ),
    ]
