# Generated by Django 2.2.14 on 2020-07-05 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='port',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1024)]),
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('traffic', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffics', to='api.Account')),
            ],
        ),
    ]
