# Generated by Django 2.2.14 on 2020-07-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200705_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic',
            old_name='last_log',
            new_name='traffic_log',
        ),
        migrations.RenameField(
            model_name='traffic',
            old_name='traffic',
            new_name='traffic_used',
        ),
    ]
